apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            proxy_pass http://api:5000;
        }

        location /webapi {
            proxy_pass http://webapi:9000;
        }
    }
