apiVersion: apps/v1
kind: Deployment
metadata:
  name: emartdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emartdb
  template:
    metadata:
      labels:
        app: emartdb
    spec:
      containers:
      - name: emartdb
        image: mysql:8.0.33
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "emartdbpass"
        - name: MYSQL_DATABASE
          value: "books"
---
apiVersion: v1
kind: Service
metadata:
  name: emartdb
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: emartdb
