name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # This will run the action when changes are pushed to the main branch
  pull_request:
    branches:
      - main

env:
  IMAGE_NAME: neeraj46665

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Use hoverkraft-tech/compose-action to build and start services
    - name: Build and start client service
      uses: hoverkraft-tech/compose-action@v0.0.0
      with:
        compose-file: './docker-compose.yml'
        services: 'client'
        up-flags: '--build'

    - name: Tag and push client image
      run: |
        docker tag client:latest ${{ env.IMAGE_NAME }}/client:latest
        docker push ${{ env.IMAGE_NAME }}/client:latest

    - name: Build and start api service
      uses: hoverkraft-tech/compose-action@v0.0.0
      with:
        compose-file: './docker-compose.yml'
        services: 'api'
        up-flags: '--build'

    - name: Tag and push api image
      run: |
        docker tag api:latest ${{ env.IMAGE_NAME }}/api:latest
        docker push ${{ env.IMAGE_NAME }}/api:latest

    - name: Build and start webapi service
      uses: hoverkraft-tech/compose-action@v0.0.0
      with:
        compose-file: './docker-compose.yml'
        services: 'webapi'
        up-flags: '--build'

    - name: Tag and push webapi image
      run: |
        docker tag webapi:latest ${{ env.IMAGE_NAME }}/webapi:latest
        docker push ${{ env.IMAGE_NAME }}/webapi:latest

    # Tear down the services after the build process
    - name: Shut down services
      uses: hoverkraft-tech/compose-action@v0.0.0
      with:
        compose-file: './docker-compose.yml'
        down-flags: '--volumes'
